### PR TITLE
Add kubevirt guest_search function

### PR DESCRIPTION
**Pull request by hkx303**
**Description**
Add kubevirt guest_search and guest related functions:

**Result:**
`{'guest_uuid': '1a559ee9-9aa4-5d2d-bc6c-ecdb8d8cxxxxx', 'hostname': 'worker-0.virtwho85.lab.pnq2.cee.redhat.com', 'guest_state': 'Running', 'guest_ip': 'worker-0.virtwho85.lab.pnq2.cee.redhat.com:xxxxx', 'uuid': '840e3e1681a0414fab55562fc3cxxxxx', 'cpu': '3', 'version': 'v1.22.0-rc.0+a44d0f0'}
`

### CODE REVIEW

**Comment by hkx303** [comment]
This PR depends on #14

**Comment by hkx303** [comment]
Please do not merge for now as we need https://github.com/VirtwhoQE/hypervisor-builder/pull/14 for this PR

**Comment by hkx303** [comment]
Remove the `do not merge` label as #14 has been merged

**Review by Junefen — COMMENTED** [review]
Looks good.

**Pull request merged**
